In [2]:
import numpy as np

In [4]:
def dropout(x, level):
    if level < 0. or level >= 1:
        raise Exception("Drouput level must be in interval [0, 1]")
    retain_prob = 1. - level
    
    sample = np.random.binomial(n=1, p=retain_prob, size=x.shape)
    print (sample)
    
    x *= sample
    print (x)
    x /= retain_prob
    
    return x

x = np.asarray([1,2,3,4,5,6,7,8,9,10], dtype=np.float32)
dropout(x, 0.4)

[1 1 0 1 1 1 1 0 0 0]
[1. 2. 0. 4. 5. 6. 7. 0. 0. 0.]


array([ 1.6666666,  3.3333333,  0.       ,  6.6666665,  8.333333 ,
       10.       , 11.666666 ,  0.       ,  0.       ,  0.       ],
      dtype=float32)